# Generated by Django 3.2.16 on 2023-01-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='account\\default_photos\\profile_image_default.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
